raise Exception('This is the helpful error message')

# returns in terminal:
#Traceback (most recent call last):
  #File "/Users/danielgallagher/python/automate_the_boring_stuff/AutomateTheBoringStuffWithPython/AutomateTheBoringStuff/raise_and_except.py", line 1, in <module>
    #raise Exception('This is the helpful error message')
#Exception: This is the helpful error message